apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: high-memory-usage
  namespace: monitoring

spec:
  groups:
    - name: memory-alerts

      rules:
        - alert: HighMemoryUsage

          expr: |
            (
              sum(container_memory_usage_bytes)
              /
              sum(machine_memory_bytes)
            ) * 100 > 85

          for: 5m

          labels:
            severity: warning

          annotations:
            summary: High memory usage detected
            description: Cluster memory usage exceeded 85%