apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: platform-alerts
  namespace: monitoring

spec:
  groups:
    - name: kubernetes

      rules:
        - alert: HighCPUUsage

          expr: sum(rate(container_cpu_usage_seconds_total[5m])) > 0.8

          for: 2m

          labels:
            severity: warning

          annotations:
            summary: High CPU usage detected