apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: cluster-recording-rules
  namespace: monitoring

spec:

  groups:

  - name: cluster

    rules:

    - record: cluster:cpu_usage:avg

      expr: |
        avg(
        rate(
        node_cpu_seconds_total{mode!="idle"}[5m]
        )
        )

    - record: cluster:memory_usage:avg

      expr: |
        avg(
        (
        node_memory_MemTotal_bytes
        -
        node_memory_MemAvailable_bytes
        )
        /
        node_memory_MemTotal_bytes
        )

    - record: cluster:pod_count

      expr: |
        count(
        kube_pod_info
        )