version: 2

updates:

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: weekly

  - package-ecosystem: "docker"

    directory: "/applications/web-frontend"

    schedule:
      interval: weekly

  - package-ecosystem: "npm"

    directory: "/applications/web-frontend"

    schedule:
      interval: weekly