apiVersion: v1

kind: Secret

metadata:

  name: alertmanager-teams

  namespace: monitoring

type: Opaque

stringData:

  api_url: |

    https://your-company.webhook.office.com/

    webhookb2/

    incomingwebhook/

    xxxxxxxxx