tempo:

  metricsGenerator:

    enabled: true

    remoteWriteUrl: http://monitoring-prometheus:9090/api/v1/write

  overrides:

      defaults:

        metrics_generator:

          processors:

            - service-graphs

            - span-metrics    

persistence:

  enabled: true

  size: 20Gi

serviceMonitor:

  enabled: true

traces:

  otlp:

    grpc:

      enabled: true

    http:

      enabled: true