apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: require-probes

spec:
  validationFailureAction: enforce

  rules:
    - name: probes-required

      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Liveness and readiness probes are required"

        pattern:
          spec:
            containers:
              - livenessProbe:
                  httpGet:
                    path: "?*"

                readinessProbe:
                  httpGet:
                    path: "?*"