apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: require-limits

spec:
  validationFailureAction: enforce

  rules:
    - name: check-limits

      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "CPU and memory limits are required"

        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"