grafana:

  enabled: true

  replicas: 1

  adminPassword: admin

  persistence:

    enabled: true

    size: 10Gi

  resources:

    requests:

      cpu: 200m

      memory: 512Mi

    limits:

      cpu: 500m

      memory: 1Gi

  serviceMonitor:

    enabled: true

  sidecar:

    dashboards:

      enabled: true

    datasources:

      enabled: false

  #additionalDataSources:
  #  - name: Loki
  #    type: loki
  #    url: http://loki:3100

  #  - name: Tempo
  #    type: tempo
  #    url: http://tempo:3200        
