apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: sealed-secrets-controller
  namespace: monitoring

spec:

  selector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets

  namespaceSelector:
    matchNames:
      - sealed-secrets

  endpoints:
    - port: http
      interval: 30s