apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-collector-config
  namespace: monitoring

data:
  otel-collector-config.yaml: |

    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      logging:

      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]