apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack

spec:

  project: platform

  source:

    repoURL: https://prometheus-community.github.io/helm-charts

    chart: kube-prometheus-stack

    targetRevision: 78.x.x

    helm:

      valueFiles:

      - values.yaml

  destination:

    namespace: monitoring

    server: https://kubernetes.default.svc

  syncPolicy:

    automated:

      prune: true

      selfHeal: true