apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: high-cpu-alert
  namespace: monitoring

spec:
  groups:
    - name: cpu-alerts

      rules:
        - alert: HighCPU

          expr: avg(rate(container_cpu_usage_seconds_total[5m])) > 0.9

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: CPU usage too high