crds:
  enabled: true

fullnameOverride: monitoring

############################################
# Prometheus Operator
############################################

prometheusOperator:
  enabled: true

############################################
# Prometheus
############################################

prometheus:

  enabled: true

  service:
    type: ClusterIP

  prometheusSpec:

    replicas: 1

    retention: 15d

    retentionSize: 10GB

    scrapeInterval: 30s

    evaluationInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorSelectorNilUsesHelmValues: false

    ruleSelectorNilUsesHelmValues: false
    
    enableRemoteWriteReceiver: true

    storageSpec:

      volumeClaimTemplate:

        spec:

          accessModes:
            - ReadWriteOnce

          resources:

            requests:

              storage: 20Gi

############################################
# Alertmanager
############################################

alertmanager:
  enabled: true
  config:
    templates:
    - /etc/alertmanager/configmaps/alertmanager-templates/*.tmpl    
  alertmanagerSpec:
    replicas: 1

    secrets:
      - alertmanager-slack
      
    configMaps:
      - alertmanager-templates

    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

############################################
# Grafana
############################################

grafana:

  enabled: true

  adminUser: admin

  adminPassword: admin123

  defaultDashboardsTimezone: browser

  persistence:

    enabled: true

    size: 10Gi

  service:

    type: ClusterIP

  sidecar:

    datasources:

      enabled: true


############################################
# kube-state-metrics
############################################

kubeStateMetrics:

  enabled: true

############################################
# node-exporter
############################################

nodeExporter:

  enabled: true

############################################
# Default Rules
############################################

defaultRules:

  create: true

############################################
# Kubernetes Components
############################################

kubeApiServer:
  #enabled: true
  enabled: false

kubeControllerManager:
  #enabled: true
  enabled: false

kubeScheduler:
  #enabled: true
  enabled: false

kubeEtcd:
  #enabled: true
  enabled: false

kubeProxy:
  #enabled: true
  enabled: false

############################################
# CoreDNS
############################################

coreDns:
  enabled: true

############################################
# Kubelet
############################################

kubelet:
  enabled: true