apiVersion: monitoring.coreos.com/v1

kind: PrometheusRule

metadata:

  name: high-cpu

  namespace: monitoring

spec:

  groups:

  - name: cpu

    rules:

    - alert: HighCPUUsage

      expr: |

        100 -

        (
          avg by(instance)

          (
            rate(
              node_cpu_seconds_total{mode="idle"}[5m]
            )
          ) * 100
        )

        > 80

      for: 5m

      labels:

        severity: warning

      annotations:

        summary: High CPU Usage

        description: CPU above 80%