apiVersion: monitoring.coreos.com/v1

kind: PrometheusRule

metadata:

  name: node-not-ready

  namespace: monitoring

spec:

  groups:

  - name: node

    rules:

    - alert: NodeNotReady

      expr: |

        kube_node_status_condition{

        condition="Ready",

        status="true"

        }

        == 0

      for: 5m

      labels:

        severity: critical

      annotations:

        summary: Node Not Ready

        description: Kubernetes node not ready