apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: slack-test
  namespace: monitoring

spec:
  groups:

  - name: slack-test

    rules:

    - alert: SlackTest

      expr: vector(1)

      for: 10s

      labels:
        severity: critical

      annotations:
        summary: Slack Integration Test

        description: Alertmanager Slack integration is working.