---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    api_url: AgCSA9NwVZkNz93rD+lN5BmUxi3v0GQQ9zkR2Tn5J5KgQjqKO5Nf7D0i9AaNPO8602HlvBUT+dpBVZNZGCLLXFP6V9qzRvq4QTdeXYo5tyN8uwixiZSUtMLNrTOxBRRWLCiUKAAQBjIse71R5Mec5icKA3QGfnoRs3tNKltbSQnQpijTTK9LP+UcGJro9+sPEq/Fjy6zBMBDr7/GcK2fTt8pT2FABdtfKL0+4+Q2kistDTPB/HhBSSt1KjByb25+8LiyKgh2vzpCQWQEVC1RO2gJjnJ14B3cgZjHgYjTQu0WZ6hne5TP5ewigKoZIo5YKsgdjRLalDmO0Js2ow5pq8HbRPgJS98/B05BbaNadZ8Ay/95HUXYz+v3t98Sdx5eqY7XlWN2lWfeUWmIBmwDILUOd/wd3MTnfOEcq1/acq72PH9C/IKHXim/6meUreh+21OA5wG7s+xX9s1V7xL0p3r5TKnInh7160Q/hBTpKKt2aASUREyNFd2edye9riT1KvMP4qWuu/NVsnpWhWyE7qjoKVqmEzsMFqivtRROGdbrYDZ+xoHUgyo55O7I6UZ/+OJcUvOsmNNe5pTl5snWZo5BvJ6jT2rG24dTuCu2zCOgi51uXIDSKqZoRnabzmKELhggUwQO7HUkQ+Ty2j5nvo/7wwgaH52l8dBKVV/cxfx2AbaOh2R7yNp9R6RfobCJqi6OL9ZGr+sLmYLJZo1E7etdB4h0UBJpPFKZfJD7fnwyV3TrRRKb2wUWN5f4K9UjgPTuFOcwZ4tMnmy/0+Gp779QPXsWMmpsPB9F1xrLmNJ0Erg=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
