---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    api_url: AgAiV1BM9tgeDKfMx3iDNDtLPbDVCcayRrGVfUsZjUFC/dH+2qaCFnFxEoj5ienBAXV5WgCkLIMhqTB0XFlm8XV58YOkLzpDM+ofmVvUJQfxqxiWR1UUwzYIPuLZhVYAEQ0yt5/MCcqvo8Ui8p6GAlsFuotNkqlhVMRf5P33mxnCAwArf1OXRFIdb0vpCSHRI9Qkuo3POWp09pMYWGe5/zEYZuuN0Err1H9grLcnAyYlJGZA2olHX6zR4B+HCmageRE2rlv1OMnxeRG+qrb25KzXSuWL4PoB/fJeq3wDy6kLGQN35SDMlWG/LmnVEB6jwjDeaUsrYrYUi+RQZbzsP1XiHiR2YVzroppmMmacwovFlda73WEgD7XJsNUUmLRNy/JkOclml/kliYnjMoIKqdsXByfBhsiABARro/K4v9zP+pII2HQ1+pgMASNE/4QGD/rZ3obBBcBxSepq2QWSc5Y4IPppCUtGh8blLuealgUZbwRSgHrkQQRis5uwQEqi/Yz7u9Qn5HLRM49A2JtumaOuElwmCc41Xh1h3J3v3zr0gXbajUBMJ5wVLXAE6m+M3lRyG8yM2rR8RHyxqfhQX/VV20yhqm5WDyIUQ+KubUbbTr8gq7KF3b2zAoJ7Pm/swGAKUweS/AkpRFbQ5j8rbbbSz5QDvoHlhLGMe0RE+TwHHq7bmlp+HaxbQa2/ooTLirxThXM7vpJNl52iDSaXbxjYQUeV2U87azTrCRWd8Mjnlnu4jh7q8WBATsEDwQsTt7nEtKgdPD61jNxbBK0ZiR96Dez1sTf1aICU8tUDbPnBuQ4=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
