apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:

  name: otel-collector

  namespace: monitoring

spec:

  selector:

    matchLabels:

      app: otel-collector

  namespaceSelector:

    matchNames:

    - monitoring

  endpoints:

  - port: grpc