apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: falco
  namespace: monitoring

spec:

  selector:

    matchLabels:
      app.kubernetes.io/name: falco

  namespaceSelector:

    matchNames:
    - falco

  endpoints:

  - port: metrics

    interval: 30s