apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: falco
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/tqnhu4/devsecops-platform.git
    targetRevision: main
    path: platform/runtime-security

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true