apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-not-ready
  namespace: monitoring

spec:
  groups:
    - name: node-alerts
      rules:
        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 2m

          labels:
            severity: critical

          annotations:
            summary: Kubernetes node not ready