apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: argocd
  namespace: monitoring

spec:

  selector:

    matchLabels:
      app.kubernetes.io/part-of: argocd

  namespaceSelector:

    matchNames:
    - argocd

  endpoints:

  - port: metrics

    interval: 30s