apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
- ../../apps/web-frontend
  
images:
- name: ghcr.io/tqnhu4/web-frontend
  newName: ghcr.io/tqnhu4/web-frontend
  newTag: a0817a021365f6dbe28cb64f39c277126bb54266
