apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
- ../../apps/web-frontend
  
images:
- name: ghcr.io/tqnhu4/web-frontend
  newName: ghcr.io/tqnhu4/web-frontend
  newTag: 84b9dbc1102c966b6d5b417ea59f7c7be0ea1aa5
