apiVersion: monitoring.coreos.com/v1

kind: PrometheusRule

metadata:

  name: pod-restart

  namespace: monitoring

spec:

  groups:

  - name: pod

    rules:

    - alert: PodRestarting

      expr: |

        increase(
        kube_pod_container_status_restarts_total[10m]
        )

        > 3

      for: 2m

      labels:

        severity: critical

      annotations:

        summary: Pod Restarting

        description: Pod restarted more than 3 times