prometheus:

  enabled: true

  prometheusSpec:

    replicas: 1

    retention: 15d

    scrapeInterval: 30s

    evaluationInterval: 30s

    enableAdminAPI: false

    resources:

      requests:

        cpu: 500m

        memory: 1Gi

      limits:

        cpu: 1

        memory: 2Gi

    storageSpec:

      volumeClaimTemplate:

        spec:

          accessModes:

            - ReadWriteOnce

          resources:

            requests:

              storage: 20Gi

alertmanager:

  enabled: true

grafana:

  enabled: true

kubeStateMetrics:

  enabled: true

nodeExporter:

  enabled: true

prometheusOperator:

  enabled: true