apiVersion: v1
kind: AlertmanagerConfig

metadata:
  name: slack
  namespace: monitoring

spec:

  route:
    receiver: slack

  receivers:

    - name: slack

      slackConfigs:

      - apiURL:

          name: alertmanager-slack

          key: api_url

        channel: "#alerts"

        sendResolved: true