apiVersion: v1
kind: Secret

metadata:

  name: alertmanager-monitoring-kube-prometheus-alertmanager

  namespace: monitoring

type: Opaque

stringData:

  alertmanager.yaml: |

    global:

    templates:

    - '/etc/alertmanager/templates/*.tmpl'    

    route:

      receiver: slack

    receivers:

    - name: slack

      slack_configs:

      #- api_url_file: /etc/alertmanager/secrets/api_url
      - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/api_url

        channel: "#alerts"

        send_resolved: true

        #title: "{{ .CommonLabels.alertname }}"

        #text: "{{ .CommonAnnotations.description }}"

        title: '{{ template "slack.title" . }}'

        text: '{{ template "slack.body" . }}'