apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-app.yaml
  #- monitoring-app.yaml
  - kube-prometheus-stack-app.yaml
  - observability-app.yaml
  - ingress-app.yaml
  - falco-app.yaml