[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/containers/*.log
    Tag               kube.*

[OUTPUT]
    Name              stdout
    Match             *