name: Platform Security Validation

on:

  push:
    branches:
      - main

  pull_request:

jobs:

  trivy-config-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy Config Scan
        uses: aquasecurity/trivy-action@master

        with:
          scan-type: config
          hide-progress: true
          severity: HIGH,CRITICAL

  kubeconform-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash

          sudo mv kustomize /usr/local/bin/

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar xz

          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes Manifests
        run: |
          kustomize build gitops/apps/web-frontend \
          | kubeconform \
            -strict \
            -ignore-missing-schemas \
            -summary \
            gitops/apps/web-frontend/*.yaml